# Generated by Django 3.1 on 2020-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('text', models.TextField()),
                ('thumbnail', models.FileField(default='', upload_to='static/photo_portfolio_app/images/')),
                ('specialties', models.BooleanField(default=False, verbose_name='Check here if you want this photos category to be included in your "specialties", on the home page and services page, otherwise if unchecked it will appear in "Other services"')),
            ],
        ),
    ]
