# Generated by Django 3.1 on 2020-08-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('image_title', models.CharField(max_length=200)),
                ('date_taken', models.DateField(blank=True, default=None, null=True, verbose_name='date taken')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_portfolio_app.category')),
                ('tags', models.ManyToManyField(null=True, to='photo_portfolio_app.Tag')),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
