# Generated by Django 3.1 on 2020-08-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0002_auto_20200813_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
