# Generated by Django 3.1 on 2020-08-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0003_auto_20200826_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='photo_portfolio_app.category'),
        ),
    ]
