# Generated by Django 3.1 on 2020-08-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0003_category_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
