# Generated by Django 3.1 on 2020-08-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0004_auto_20200826_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
