# Generated by Django 3.1 on 2020-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0004_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=100, unique=True),
        ),
    ]
