# Generated by Django 3.1 on 2020-08-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0005_auto_20200826_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
    ]
