# Generated by Django 3.1 on 2020-08-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0005_photo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
    ]
