# Generated by Django 3.1 on 2020-08-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0006_remove_comment_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='approved',
        ),
    ]
