# Generated by Django 3.1 on 2020-08-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0007_photo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateField(auto_now_add=True),
        ),
    ]
