# Generated by Django 3.1 on 2020-08-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0008_auto_20200813_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='specialties',
            field=models.BooleanField(default=False),
        ),
    ]
