# Generated by Django 3.1 on 2020-08-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0009_category_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.FileField(default='', upload_to='static/photo_portfolio_app/images/'),
        ),
    ]
