# Generated by Django 3.1 on 2020-08-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0010_auto_20200814_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
