# Generated by Django 3.1 on 2020-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0012_photo_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Check this if you want picture to appear with the selected few in the home page'),
        ),
    ]
