# Generated by Django 3.1 on 2020-08-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0013_auto_20200814_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Check this if you want picture to be shown as featured on the home page'),
        ),
    ]
