# Generated by Django 3.1 on 2020-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0014_auto_20200814_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_title',
            field=models.CharField(max_length=200, verbose_name='A short title, max two words'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, verbose_name='A short title, max two words'), max_length=100, unique=True),
        ),
    ]
