# Generated by Django 3.1 on 2020-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0015_auto_20200814_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='specialties',
            field=models.BooleanField(default=False, verbose_name='Check here if you want this photos category to be included in your specialties, on the home page and services page'),
        ),
    ]
