# Generated by Django 3.1 on 2020-08-19 10:55

from django.db import migrations, models
import photo_portfolio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0019_auto_20200817_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(default='', max_length=200, verbose_name=photo_portfolio_app.models.Category),
        ),
    ]
