# Generated by Django 3.1 on 2020-08-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0022_auto_20200820_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='photo_portfolio_app.category'),
        ),
    ]
