# Generated by Django 3.1 on 2020-08-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_portfolio_app', '0025_auto_20200820_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
